# Generated by Django 3.2.3 on 2021-05-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packs',
            new_name='Pack',
        ),
    ]
